# -*- coding: utf-8 -*-
"""pygame 이미지 load 및 크기 조정

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gV_qtekrYE8pUZKMiOjMnJLejfOKnof
"""

import pygame

# 1. 초기화 -> 변수 선언
pygame.init()
# 2. 게임 화면 설정 -> 크기 고정
size = [400, 750]
screen = pygame.display.set_mode(size)

title = "PyGameExam"
pygame.display.set_caption(title)

# 3. 게임 화면 내에서의 설정 -> 변수
clock = pygame.time.Clock()

color = (0, 0, 0)
black = (0, 0, 0)
white = (255, 255, 255)
color1 = (112, 103, 76)

hero = pygame.image.load("C:\\Users\\USER\\Pictures\\hero2.png").convert_alpha()
hero = pygame.transform.scale(hero, (80, 80))

k = 0

# 4. 메인이벤트
system_exit = 0
while(system_exit == 0):
    #  4-1. FPS(Frame per Sec) 설정
    clock.tick(2)
    
    #  4-2. 입력(키보드, 마우스)의 감지
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            system_exit = 1

    #  4-3. 입력, 시간에 따른 변화
    k += 1
    
    #  4-4. 전사작업(그리기)
    screen.fill(black)
    screen.blit(hero, (100, 100))

    #  4-5. 업데이트
    pygame.display.flip()

# 5. 종료
pygame.quit()